import type { Metadata } from "next";
import { Alegreya, Alegreya_Sans, Caveat, JetBrains_Mono } from "next/font/google";
import Providers from "@/components/Providers";
import "./globals.css";

const paperBody = Alegreya_Sans({
  variable: "--font-paper-body",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  display: "swap",
});

const paperDisplay = Alegreya({
  variable: "--font-paper-display",
  subsets: ["latin"],
  weight: ["500", "700", "800"],
  display: "swap",
});

const paperScript = Caveat({
  variable: "--font-paper-script",
  subsets: ["latin"],
  weight: ["600", "700"],
  display: "swap",
});

const paperMono = JetBrains_Mono({
  variable: "--font-paper-mono",
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Inflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${paperBody.variable} ${paperDisplay.variable} ${paperScript.variable} ${paperMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
