import type { Metadata } from "next";
import { Alegreya, Alegreya_Sans, Caveat, JetBrains_Mono } from "next/font/google";
import type { Session } from 'next-auth';
import Providers from "@/components/Providers";
import "./globals.css";

const paperBody = Alegreya_Sans({
  variable: "--font-paper-body",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  display: "swap",
});

const paperDisplay = Alegreya({
  variable: "--font-paper-display",
  subsets: ["latin"],
  weight: ["500", "700", "800"],
  display: "swap",
});

const paperScript = Caveat({
  variable: "--font-paper-script",
  subsets: ["latin"],
  weight: ["600", "700"],
  display: "swap",
});

const paperMono = JetBrains_Mono({
  variable: "--font-paper-mono",
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Inflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isBypass = process.env.AUTH_BYPASS === 'true';
  const session: Session | null = isBypass
    ? {
        user: {
          id: process.env.AUTH_BYPASS_USER_ID || 'test-user',
          email: process.env.AUTH_BYPASS_USER_EMAIL || 'test-user@local.dev',
          name: process.env.AUTH_BYPASS_USER_NAME || 'Test User',
        },
        expires: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
      }
    : null;

  return (
    <html lang="en">
      <body
        className={`${paperBody.variable} ${paperDisplay.variable} ${paperScript.variable} ${paperMono.variable} antialiased`}
      >
        <Providers session={session} isBypass={isBypass}>{children}</Providers>
      </body>
    </html>
  );
}
